name: "clip_preprocess"
backend: "dali"
max_batch_size: 64

input [
  {
    name: "IMAGE_INPUT"
    data_type: TYPE_UINT8
    dims: [ -1 ] # Variable length raw bytes
  }
]

output [
  {
    name: "PIXEL_VALUES"
    data_type: TYPE_FP32
    dims: [ 3, 224, 224 ]
  }
]
instance_group [
  {
    count: 1
    kind: KIND_GPU
  }
]
